### ISSUE TITLE
windows构建的exe运行报错

### ISSUE THREAD

**Issue by dongsir** [iview/iview-cli#7]
通过`npm run build:win64`后运行生成的iView.exe

> [Window Title]
> Error
> 
> [Main Instruction]
> A JavaScript error occured in the main process
> 
> [Content]
> Uncaught Exception:
> D:\Vue\iview-cli\iView-win32-x64\resources\app\main.js:1
> (function (exports, require, module, __filename, __dirname) { const { app, BrowserWindow, Menu } = require('electron');
>                                                                     ^
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:411:25)
>     at Object.Module._extensions..js (module.js:446:10)
>     at Module.load (module.js:353:32)
>     at Function.Module._load (module.js:308:12)
>     at Object.<anonymous> (D:\WorkSpace\Vue\iview-cli\iView-win32-x64\resources\atom.asar\browser\lib\init.js:106:10)
>     at Object.<anonymous> (D:\WorkSpace\Vue\iview-cli\iView-win32-x64\resources\atom.asar\browser\lib\init.js:108:4)
>     at Module._compile (module.js:428:26)
>     at Object.Module._extensions..js (module.js:446:10)
>     at Module.load (module.js:353:32)
> 
> [确定]
>

**Comment by marszoolong** [comment]
>> 直接下载exe不好吗？
